// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" }
import * as $0 from "./routes/api/[...path].ts"
import * as $1 from "./routes/index.tsx"
import * as $2 from "./routes/save.tsx"
import * as $$0 from "./islands/Counter.tsx"
import * as $$1 from "./islands/Save.tsx"
import * as $$2 from "./islands/Search.tsx"

const manifest = {
  routes: {
    "./routes/api/[...path].ts": $0,
    "./routes/index.tsx": $1,
    "./routes/save.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Save.tsx": $$1,
    "./islands/Search.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
